### ISSUE TITLE
Feature Request: send funds to the Wallet SK account if it doesn't exist yet (on testnet)

### ISSUE THREAD

**Issue by vitchor** [stellar-deprecated/sep24-demo-client#136]
It would be great if the demo client funded the account, relative to the Wallet SK, if this wasn't done yet. This would only work for testnet.

This should solve the issue of old accounts (from before testnet resets) breaking the demo client links.

Another option: maybe we could have a clearer error message for those cases.

**Comment by msfeldstein** [comment]
Both of these are good ideas.  A 'fund' button next to 'generate' on the config screen, and a clear error message that the account doesn't exist rather than a 404
