### ISSUE TITLE
Support popups instead of iframes

### ISSUE THREAD

**Issue by msfeldstein** [stellar-deprecated/sep24-demo-client#147]
iframes are causing some technical issues due to 3rd party cookies in certain browsers, as well as questionable user experience.  We should investigate using popups, similar to oauth workflow, instead of iframes.

**Comment by JakeUrban** [comment]
I'm talking to Gleb from LOBSTR about implementing this change in their wallet and he had a concern:

> a concern on our end is that some browsers / plugins are blocking pop-ups quite aggressively. 
we even used to open iframes automatically - now we'll need to make sure it has a user interaction, e..g "Start" button.

I think browsers being wary of popups is fine as long as they ask the user for permission when the client is trying to open one. But do any browsers outright block them without giving the user a chance to whitelist it? I can look into this if we're unsure.

**Comment by JakeUrban** [comment]
From [javascript.info](https://javascript.info/popup-windows):

> Most browsers block popups if they are called outside of user-triggered event handlers like onclick.

So assuming most wallets open the popup as a result of the user clicking some kind of "Start" or "Deposit" button, this shouldn't be much of an issue.

**Comment by msfeldstein** [comment]
yeah i don't think its a big issue, OAuth is a pretty common and similar
pattern that doesn't seem to be a problem.

**Comment by vcarl** [comment]
FYI the solution I had for popups when I implemented SEP6 was that you can create the popup separately from where you tell it what to display. We set up a singleton popup helper so we could easily control the window, then opened it from a user interaction and told it where to go once we had that information.
