### ISSUE TITLE
No token returned from auth doesn't reset the auth flow

### ISSUE THREAD

**Issue by kalepail** [stellar-deprecated/sep24-demo-client#154]
### What did you expect to see?
When going through the auth flow, if you wait till after the transaction is valid the flow continues on as if the auth didn't fail leaving you in a stuck state moving forward with no JWT.

### What did you see instead?
A failed auth flow for a JWT should loop you back to signing a new transaction.

![Screen Shot 2020-01-31 at 2 54 00 PM](https://user-images.githubusercontent.com/4383610/73570602-a4afd480-443a-11ea-8f4f-4a1ed1653192.png)

**Comment by msfeldstein** [comment]
We recommend using strict mode so any failures stop the flow.  Once there's some type of failure we don't really give you an option to get back on track besides reloading the page.  This sort of edge case flow is outside the bounds of the tool

**Comment by kalepail** [comment]
👍 Good to know. Thanks!
