### ISSUE TITLE
Re-requesting /more_info unnecessarily

### ISSUE THREAD

**Issue by JakeUrban** [stellar-deprecated/sep24-demo-client#156]
The final form submission during the interactive flow will redirect to `/more_info` on success, but the demo client re-requests it, making it look like the deposit memo code changes for the transaction. This is a less-than-ideal UX and was pointed out by @tyvdh 

Solution: Don't request `/more_info` until the transaction is no longer has a `pending_user_transfer_start` status.

**Comment by msfeldstein** [comment]
why does the deposit memo code change?

**Comment by JakeUrban** [comment]
The original deposit memo code is not being stored permanently, a new code is generated every time `/more_info` is requested and the transaction is still in `pending_user_transfer_start`.

Since the instructions shown are just to provide an example for how other anchors may identify incoming deposits, I didn't think it was worth creating a new model in `example` to persist it.

**Comment by msfeldstein** [comment]
if this is truly not necessary (because the deposit is automatically
completed?) can we generate the deposit memo as a hash of the transaction
ID or something?  I don't like that this can change and is random it could
cause confusion to anyone looking to it as a reference

**Comment by kalepail** [comment]
Hash off the id seems ideal, that’s what I was hoping it was originally.

**Comment by JakeUrban** [comment]
Yea that makes sense. Closing.
