### ISSUE TITLE
Auto-generate secret key

### ISSUE THREAD

**Issue by msfeldstein** [stellar-deprecated/sep24-demo-client#45]
Allow users to autogenerate a secret key to use in the tool since it doesn't really matter what they're using

**Comment by msfeldstein** [comment]
This isn't possible now since we use custom assets.  You'll need to create and fund the account yourself.

**Comment by tomerweller** [comment]
@msfeldstein why is this a problem? why not have the tool create the account and fund it for you? (assuming testnet)

**Comment by msfeldstein** [comment]
I'm not sure why i closed this.  The deposit functionality i'm working on should cover this though.
