### ISSUE TITLE
Add `NETWORK_PASSPHRASE` configuration

### ISSUE THREAD

**Issue by tomerweller** [stellar-deprecated/sep24-demo-client#5]
And use that when signing transactions.

**Comment by msfeldstein** [comment]
Does this just mean allow TESTNET or MAINNET?  are there any other passphrases people would want to use?

**Comment by tomerweller** [comment]
https://www.stellar.org/developers/guides/concepts/networks.html#network-passphrases
For simplicity you can just switch between the two preset ones, though a complete solution would include a field to put in a custom one. See how the laboratory does it.

**Comment by tomerweller** [comment]
The current main net config is good enough. Closing.
