### ISSUE TITLE
Config box partially hidden in Firefox 68.0 on Linux

### ISSUE THREAD

**Issue by ire-and-curses** [stellar-deprecated/sep24-demo-client#53]
On sep6.stellar.org:

![image](https://user-images.githubusercontent.com/1606404/63114704-5a996c00-bf4a-11e9-87e6-a00bbe9c63da.png)

I can see the whole thing if I go full-screen though (F11)

**Comment by msfeldstein** [comment]
are you looking at this on a netbook, perhaps a Palm Foleo?

**Comment by msfeldstein** [comment]
@brunomuler anything we can do about smaller screens?

**Comment by ire-and-curses** [comment]
No, it's a [System76 Galago Pro](https://system76.com/laptops/galago).

**Comment by brunomlr** [comment]
Yeah, the PR #58 should fix it. Please let me know if this still happens after it.

**Comment by ire-and-curses** [comment]
Tested and it works. :+1:
